### ISSUE TITLE
Some flows scheduled with print-output (.lst) on AppServers are not shown in Job Monitor

### ISSUE THREAD

**Issue by StefEOM** [eomnl/sas-jobmon#18]
Some flows that are scheduled with a print option ("...\BatchServer\sasbatch.bat" -log "...log" -print "....lst" -batch ...") are not shown in Job Monitor.
This can happen, when the print-option command (*.lst) includes a blank. For example when the AppServer-(folder)name contains a blank (C:\SAS\SASConfig\SASApp Unicode\print.lst)

**Comment by bheinsius** [comment]
Please supply the fix

**Comment by StefEOM** [comment]
In **dimon_pre.bat** please remove the quotes around **DIMON_SASLSTFILE!**

So, change line 121-122 from:
`    IF DEFINED DIMON_SASLOGFILE SET DIMON_SETSASLOGFILE=-set SASLOGFILE "!DIMON_SASLOGFILE!"
    IF DEFINED DIMON_SASLSTFILE SET DIMON_SETSASLSTFILE=-set SASLSTFILE "!DIMON_SASLSTFILE!"`
to:
`    IF DEFINED DIMON_SASLOGFILE SET DIMON_SETSASLOGFILE=-set SASLOGFILE "!DIMON_SASLOGFILE!"
    IF DEFINED DIMON_SASLSTFILE SET DIMON_SETSASLSTFILE=-set SASLSTFILE !DIMON_SASLSTFILE!
`

![image](https://user-images.githubusercontent.com/39827258/234595041-e543f920-b8e8-4dd9-8b19-b078d8437b1c.png)
